<?php
/**
 * @file
 * tl_univers.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function tl_univers_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => '1',
  'title' => 'Airsoft',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '16ae78e0-95d7-40fd-a6a5-637cafa1ba0c',
  'type' => 'groupe',
  'language' => 'fr',
  'created' => '1319815182',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '18d2704f-d900-45d7-8beb-5e51aeb29cb0',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Description brève à l\'attention des connaisseurs',
        'summary' => '',
        'format' => 'plain_text',
        'safe_value' => '<p>Description brève à l&#039;attention des connaisseurs</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_group_type' => array(
    'und' => array(
      0 => array(
        'value' => 'univers',
      ),
    ),
  ),
  'group_access' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'og_roles_permissions' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'group_group' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'field_icon' => array(),
  'cid' => '0',
  'last_comment_timestamp' => '1319815182',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'superadmin',
  'picture' => '0',
  'data' => 'b:0;',
  'date' => '2011-10-28 17:19:42 +0200',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Jeux de Rôle',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => 'ac71435f-5346-4e90-9af9-67703817e410',
  'type' => 'groupe',
  'language' => 'fr',
  'created' => '1319815124',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '1dfd3e87-dbda-4d8f-9ceb-b932b75a3a31',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Description brève à l\'attention des connaisseurs',
        'summary' => '',
        'format' => 'plain_text',
        'safe_value' => '<p>Description brève à l&#039;attention des connaisseurs</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_group_type' => array(
    'und' => array(
      0 => array(
        'value' => 'univers',
      ),
    ),
  ),
  'group_access' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'og_roles_permissions' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'group_group' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'field_icon' => array(
    'und' => array(
      0 => array(
        'fid' => '1',
        'alt' => '',
        'title' => '',
        'width' => '1704',
        'height' => '2272',
        'uid' => '1',
        'filename' => 'fotolia_2085337_l.jpg',
        'uri' => 'public://fotolia_2085337_l.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '791005',
        'status' => '1',
        'timestamp' => '1327871880',
        'uuid' => 'e314cacc-6915-4718-9afd-5de39bd1dfcd',
      ),
    ),
  ),
  'cid' => '0',
  'last_comment_timestamp' => '1319815124',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'superadmin',
  'picture' => '0',
  'data' => 'b:0;',
  'date' => '2011-10-28 17:18:44 +0200',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Jeux de Plateau',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => 'aad000ef-b6ba-48cd-93fb-7ab626a8da70',
  'type' => 'groupe',
  'language' => 'fr',
  'created' => '1319815241',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '57e6ae09-a265-4b6d-acb1-86360a22139e',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Description brève à l\'attention des connaisseurs',
        'summary' => '',
        'format' => 'plain_text',
        'safe_value' => '<p>Description brève à l&#039;attention des connaisseurs</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_group_type' => array(
    'und' => array(
      0 => array(
        'value' => 'univers',
      ),
    ),
  ),
  'group_access' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'og_roles_permissions' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'group_group' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'field_icon' => array(),
  'cid' => '0',
  'last_comment_timestamp' => '1319815241',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'superadmin',
  'picture' => '0',
  'data' => 'b:0;',
  'date' => '2011-10-28 17:20:41 +0200',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Soirées Enquêtes',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '5920f5df-ddc8-4e80-9cc4-2143a77d9b70',
  'type' => 'groupe',
  'language' => 'fr',
  'created' => '1319815168',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '683354a6-a13b-4435-a6f6-6fc56c7d0924',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Description brève à l\'attention des connaisseurs',
        'summary' => '',
        'format' => 'plain_text',
        'safe_value' => '<p>Description brève à l&#039;attention des connaisseurs</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_group_type' => array(
    'und' => array(
      0 => array(
        'value' => 'univers',
      ),
    ),
  ),
  'group_access' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'og_roles_permissions' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'group_group' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'field_icon' => array(),
  'cid' => '0',
  'last_comment_timestamp' => '1319815168',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'superadmin',
  'picture' => '0',
  'data' => 'b:0;',
  'date' => '2011-10-28 17:19:28 +0200',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Jeux de Figurines',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => 'ba901e28-20c8-4cfe-b2b6-655cecc27eaa',
  'type' => 'groupe',
  'language' => 'fr',
  'created' => '1319815199',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '8bcaa9ba-c6b7-499f-827e-6f372e6753e7',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Description brève à l\'attention des connaisseurs',
        'summary' => '',
        'format' => 'plain_text',
        'safe_value' => '<p>Description brève à l&#039;attention des connaisseurs</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_group_type' => array(
    'und' => array(
      0 => array(
        'value' => 'univers',
      ),
    ),
  ),
  'group_access' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'og_roles_permissions' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'group_group' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'field_icon' => array(),
  'cid' => '0',
  'last_comment_timestamp' => '1319815199',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'superadmin',
  'picture' => '0',
  'data' => 'b:0;',
  'date' => '2011-10-28 17:19:59 +0200',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Jeux de Cartes à Collectionner',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '1f6781df-1ac7-4509-99a2-ca29405a45c7',
  'type' => 'groupe',
  'language' => 'fr',
  'created' => '1319815390',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'b40cc80d-b536-45a7-92e1-8fe6bca7a65e',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Description brève à l\'attention des connaisseurs',
        'summary' => '',
        'format' => 'plain_text',
        'safe_value' => '<p>Description brève à l&#039;attention des connaisseurs</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_group_type' => array(
    'und' => array(
      0 => array(
        'value' => 'univers',
      ),
    ),
  ),
  'group_access' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'og_roles_permissions' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'group_group' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'field_icon' => array(),
  'cid' => '0',
  'last_comment_timestamp' => '1319815390',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'superadmin',
  'picture' => '0',
  'data' => 'b:0;',
  'date' => '2011-10-28 17:23:10 +0200',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Semi-Réel',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '1ff1082e-de78-4b67-809c-4d915a22bc01',
  'type' => 'groupe',
  'language' => 'fr',
  'created' => '1319815424',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'bcf4e781-f8f7-4676-9a67-6ff9edc46ff3',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Description brève à l\'attention des connaisseurs',
        'summary' => '',
        'format' => 'plain_text',
        'safe_value' => '<p>Description brève à l&#039;attention des connaisseurs</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_group_type' => array(
    'und' => array(
      0 => array(
        'value' => 'univers',
      ),
    ),
  ),
  'group_access' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'og_roles_permissions' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'group_group' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'field_icon' => array(),
  'cid' => '0',
  'last_comment_timestamp' => '1319815424',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'superadmin',
  'picture' => '0',
  'data' => 'b:0;',
  'date' => '2011-10-28 17:23:44 +0200',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Grandeurs Natures',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => 'acf7dfa2-f7bf-4e29-8b66-bf9b28f81a2c',
  'type' => 'groupe',
  'language' => 'fr',
  'created' => '1319815151',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'cb923d11-3a51-4509-80ae-36d9d1b889c0',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Description brève à l\'attention des connaisseurs',
        'summary' => '',
        'format' => 'plain_text',
        'safe_value' => '<p>Description brève à l&#039;attention des connaisseurs</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_group_type' => array(
    'und' => array(
      0 => array(
        'value' => 'univers',
      ),
    ),
  ),
  'group_access' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'og_roles_permissions' => array(
    'und' => array(
      0 => array(
        'value' => '0',
      ),
    ),
  ),
  'group_group' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'field_icon' => array(),
  'cid' => '0',
  'last_comment_timestamp' => '1319815151',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'superadmin',
  'picture' => '0',
  'data' => 'b:0;',
  'date' => '2011-10-28 17:19:11 +0200',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Comité d\'Administration',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => 'e933975d-fa20-4ee5-921c-ed33e28d7174',
  'type' => 'groupe',
  'language' => 'fr',
  'created' => '1319815472',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'd9475fec-ae94-4a53-aa67-f1255a3e19c4',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Description brève à l\'attention des connaisseurs',
        'summary' => '',
        'format' => 'plain_text',
        'safe_value' => '<p>Description brève à l&#039;attention des connaisseurs</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_group_type' => array(
    'und' => array(
      0 => array(
        'value' => 'groupe_travail',
      ),
    ),
  ),
  'group_access' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'og_roles_permissions' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'group_group' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'field_icon' => array(),
  'cid' => '0',
  'last_comment_timestamp' => '1319815472',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'superadmin',
  'picture' => '0',
  'data' => 'b:0;',
  'date' => '2011-10-28 17:24:32 +0200',
);
  return $nodes;
}
