<?php
/**
 * @file
 * Code for the TL Config Base feature.
 */

include_once('tl_config_base.features.inc');

/*
 * Implements hook_date_format_types().
 */
function tl_config_base_date_format_types() {
    return array(
        'date_court' => t('Date court'),
        'date_medium' => t('Date medium'),
        'date_long' => t('Date long'),
    );
}

/*
 * Implements hook_date_formats().
 */
function tl_config_base_date_formats() {
    $formats = array();

    // Short date formats.
    $formats[] = array(
        'type' => 'date_court',
        'format' => 'd/m/Y',
        'locales' => array(),
    );
    $formats[] = array(
        'type' => 'date_medium',
        'format' => 'D d/m/Y',
        'locales' => array(),
    );
    $formats[] = array(
        'type' => 'date_long',
        'format' => 'l j F Y',
        'locales' => array(),
    );

    return $formats;
}
